### Procesar una unica linea, con un tipo de registro
POST {{url}}/record-structure
Content-Type: application/json

{
  "line": "001ABC123EJEMPLO DE REGISTRO    00000012345.6791031052025",
  "lineIdentifier": "001",
  "recordFields": [
    {
      "order": 4,
      "length": 14,
      "type": "DECIMAL",
      "format": "FIXED_POINT_NUMBERS"
    },
    {
      "order": 1,
      "length": 3,
      "type": "INTEGER",
      "format": "DEFAULT"
    },
    {
      "order": 2,
      "length": 6,
      "type": "STRING",
      "format": "DEFAULT"
    },
    {
      "order": 6,
      "length": 8,
      "type": "DATE",
      "format": "DDMMYYYY"
    },
    {
      "order": 3,
      "length": 23,
      "type": "STRING",
      "format": "DEFAULT"
    },
    {
      "order": 5,
      "length": 3,
      "type": "DECIMAL",
      "format": "DEFAULT"
    }
  ]
}

>> record-structure/response.json
