### Procesar una unica linea, con un tipo de registro
POST {{url}}/record-structure
Content-Type: application/json

{
  "line": "001ABC123EJEMPLO DE REGISTRO    00000012345.6791031052025",
  "lineIdentifier": "001",
  "recordFields": [
    {
      "order": 4,
      "length": 14,
      "type": "DECIMAL",
      "format": "FIXED_POINT_NUMBERS"
    },
    {
      "order": 1,
      "length": 3,
      "type": "INTEGER",
      "format": "DEFAULT"
    },
    {
      "order": 2,
      "length": 6,
      "type": "STRING",
      "format": "DEFAULT"
    },
    {
      "order": 6,
      "length": 8,
      "type": "DATE",
      "format": "DDMMYYYY"
    },
    {
      "order": 3,
      "length": 23,
      "type": "STRING",
      "format": "DEFAULT"
    },
    {
      "order": 5,
      "length": 3,
      "type": "DECIMAL",
      "format": "DEFAULT"
    }
  ]
}

>> record-structure/response.json

### Procesar un archivo, con un tipo de registro
POST {{url}}/record-structure/file
Content-Type: application/json

{
  "filePath": "record-structure-test.txt",
  "lineIdentifier": "001",
  "recordFields": [
    {
      "order": 4,
      "length": 14,
      "type": "DECIMAL",
      "format": "FIXED_POINT_NUMBERS",
      "columnName": "Importe"
    },
    {
      "order": 1,
      "length": 3,
      "type": "INTEGER",
      "format": "DEFAULT",
      "columnName": "Identificador"
    },
    {
      "order": 2,
      "length": 6,
      "type": "STRING",
      "format": "DEFAULT",
      "columnName": "Referencia"
    },
    {
      "order": 6,
      "length": 8,
      "type": "DATE",
      "format": "DDMMYYYY",
      "columnName": "Fecha"
    },
    {
      "order": 3,
      "length": 23,
      "type": "STRING",
      "format": "DEFAULT",
      "columnName": "Descripción"
    },
    {
      "order": 5,
      "length": 3,
      "type": "DECIMAL",
      "format": "DEFAULT",
      "columnName": "IVA"
    }
  ]
}

>> record-structure/file-response.json

### Generar un archivo CSV a partir de un archivo, con un tipo de registro
POST {{url}}/record-structure/generate-csv
Content-Type: application/json

{
  "filePath": "record-structure-test.txt",
  "lineIdentifier": "001",
  "recordFields": [
    {
      "order": 4,
      "length": 14,
      "type": "DECIMAL",
      "format": "FIXED_POINT_NUMBERS",
      "columnName": "Importe"
    },
    {
      "order": 1,
      "length": 3,
      "type": "INTEGER",
      "format": "DEFAULT",
      "columnName": "Identificador"
    },
    {
      "order": 2,
      "length": 6,
      "type": "STRING",
      "format": "DEFAULT",
      "columnName": "Referencia"
    },
    {
      "order": 6,
      "length": 8,
      "type": "DATE",
      "format": "DDMMYYYY",
      "columnName": "Fecha"
    },
    {
      "order": 3,
      "length": 23,
      "type": "STRING",
      "format": "DEFAULT",
      "columnName": "Descripción"
    },
    {
      "order": 5,
      "length": 3,
      "type": "DECIMAL",
      "format": "DEFAULT",
      "columnName": "IVA"
    }
  ]
}

>> record-structure/csv-response.json
